
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      LAN:
        ipv4_address: 192.168.1.555
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    env_file:
      - .env
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media
      - /transcode_cache:/temp
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"

#    deploy:
#      resources:
#        reservations:

networks:
  LAN:
    external:
      true

volumes:
  server:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,vers=4
      device: ":/volume1/Network Drive/docker_configs/tdarr-nvr_server"

  configs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,vers=4
      device: ":/volume1/Network Drive/docker_configs/tdarr-nvr_configs"

  logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,vers=4
      device: ":/volume1/Network Drive/docker_data/tdarr-nvr_logs"

  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,vers=4
      device: ":/volume1/Network Drive/docker_data/tdarr-nvr_media"

  transcode_cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,vers=4
      device: ":/volume1/Network Drive/docker_data/tdarr-nvr_transcode_cache"