services:
  olla:
    image: ghcr.io/thushan/olla:latest
    container_name: olla
#    env_file:
#      - .env
    ports:
      - "40114:40114"   # more for personal reference than it being needed since it has its own dedicated IP.
    restart: unless-stopped
    networks:
      LAN:
        ipv4_address: 192.168.1.49
    environment:
        - CONFIG=config.yaml
    # guarantee logs are visible
    tty: true
    stdin_open: true





    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"

networks:
  LAN:
    external:
      true

volumes:
  ShinobiSQL:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/shinobi/ShinobiSQL"
    