version: '3'
services:
  shinobi-sql:
    image: mysql:5.7
    volumes:
      - $HOME/ShinobiSQL:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ccio
      - MYSQL_USER=majesticflame
      - MYSQL_PASSWORD=1234
    restart: unless-stopped
