services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
<<<<<<< HEAD
    network_mode:
      LAN:
        ipv4_address: 192.168.1.153
=======
>>>>>>> refs/remotes/origin/main
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
<<<<<<< HEAD
    environment:
      - PUID=1000
      - PGID=1000
      - PAPERLESS_AI_PORT=${PAPERLESS_AI_PORT:-3000}
      - RAG_SERVICE_URL=http://localhost:8000
      - RAG_SERVICE_ENABLED=true
=======
    env_file:
      - .env
>>>>>>> refs/remotes/origin/main
    ports:
      - "3000:${PAPERLESS_AI_PORT:-3000}"
    volumes:
      - paperless-ai_data:/data
<<<<<<< HEAD
=======
    networks:
      LAN:
        ipv4_address: 192.168.1.153





>>>>>>> refs/remotes/origin/main
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
<<<<<<< HEAD
    network_mode:
      LAN:
        ipv4_address: 192.168.1.157

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    network_mode:
      LAN:
        ipv4_address: 192.168.1.158

=======
    networks:
      LAN:
        ipv4_address: 192.168.1.157






  db:
    image: docker.io/library/postgres:17
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      LAN:
        ipv4_address: 192.168.1.158






>>>>>>> refs/remotes/origin/main
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
<<<<<<< HEAD
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    network_mode:
      LAN:
        ipv4_address: 192.168.1.154

=======
    env_file:
#      - docker-compose.env
      - .env
    networks:
      LAN:
        ipv4_address: 192.168.1.154






    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"

networks:
  LAN:
    external:
      true

>>>>>>> refs/remotes/origin/main
volumes:
  paperless-ai_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/paperless-ai_data"

<<<<<<< HEAD
=======
  redisdata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/redisdata"

  pgdata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/pgdata"

>>>>>>> refs/remotes/origin/main
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/data"

  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/media"
<<<<<<< HEAD

  pgdata:

  redisdata:

=======
>>>>>>> refs/remotes/origin/main
