###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

services:
  actual-development:
    build: .
    image: actual-development
    restart: 'always'
    networks:
      LAN:
        ipv4_address: 192.168.1.177
    ports:
      - 3001:3001
    volumes:
      - '.:/app'

networks:
  LAN:
    external:
      true


# https://actualbudget.org/docs/install/docker/