# https://github.com/monicahq/monica.git
# https://beta.monicahq.com/

services:
  laravel.test: &app
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    env_file:
      - .env
    volumes:
      - '.:/var/www/html'
    networks:
      - LAN
    depends_on:
      - mariadb
      - redis
      - memcached
      - meilisearch
      - mailpit
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"


  laravel.queue:
    <<: *app
    command: 'php artisan queue:work --sleep=10 --timeout=0 --tries=3 --queue=high,default,low'
  laravel.cron:
    <<: *app
    command: 'php artisan schedule:run'


  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    env_file:
      - .env
    volumes:
      - 'sail-mariadb:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - LAN
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"







  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - LAN
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"







  memcached:
    image: 'memcached:alpine'
    ports:
      - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
    networks:
      - LAN
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"



  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - LAN
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - LAN
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"








networks:
  LAN:
    external:
      true





volumes:
  mariadb:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/monica/mariadb"
  redis:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/monica/redis"
  meilisearch:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/monica/meilisearch"



