# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    env_file:
      - .env
    ## the container's port must be the same with the STASH_PORT in the .env file
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    networks:
      LAN:
        ipv4_address: 192.168.1.555

    volumes:
      - localtime:/etc/localtime:ro
      ## Keep configs, scrapers, and plugins here.
      - config:/root/.stash
      ## Point this at your collection.
      - data:/data
      ## This is where your stash's metadata lives
      - metadata:/metadata
      ## Any other cache content.
      - cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - generated:/generated


    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"


# For networking, you'll want to reserve of block of 16 IP addresses, (/28 or .240)
networks:
  LAN:
    external:
      true


volumes:
  localtime:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/stash/localtime"

  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_config/stash/config"

  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/stash/data"

  metadata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/stash/metadata"

  cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/stash/cache"

  blobs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/stash/blobs"

  generated:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.247,rw,nolock,noatime,vers=4
      device: ":/volume1/Network Drive/docker_data/stash/generated"


